import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ALL_PROBLEMS } from "./data/problems";
import { TECH_NODES } from "./data/tech";
import { BLUEPRINTS } from "./data/blueprints";
import { ITEM_DEFINITIONS } from "./data/items";
import { BADGES } from "./data/badges";

/**
 * Generates supabase/seed.sql from the typed data files.
 *
 * The SQL is committed, so `psql -f supabase/seed.sql` works with no Node
 * toolchain. Regenerate with `pnpm seed:sql` after editing anything in
 * scripts/data — the verifiers run first, so a broken expectation cannot reach
 * the file.
 */

/** Single quotes are doubled; that is the whole of SQL string escaping. */
function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function textArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `ARRAY[${values.map(q).join(", ")}]::text[]`;
}

function json(value: unknown): string {
  return `${q(JSON.stringify(value))}::jsonb`;
}

const lines: string[] = [];

lines.push(
  "-- CodeNation seed data.",
  "--",
  "-- GENERATED by scripts/generate-seed.ts. Do not edit by hand; edit the typed",
  "-- sources in scripts/data/ and run `pnpm seed:sql`.",
  "--",
  "-- Every problem's expected output is verified against a working reference",
  "-- solution by scripts/verify-seed.ts before this file is written.",
  "--",
  "-- Idempotent: every statement is an upsert on a natural key, so running it",
  "-- twice is a no-op rather than a duplicate-key error.",
  "",
  "begin;",
  "",
);

// ---------------------------------------------------------------------------
lines.push("-- ---------- tech nodes ----------", "");
for (const node of TECH_NODES) {
  lines.push(
    `insert into public.tech_nodes (slug, name, tier, branch, description, cost, requires, topics, solves_required, pos_x, pos_y)`,
    `values (${q(node.slug)}, ${q(node.name)}, ${node.tier}, ${q(node.branch)}, ${q(node.description)}, ${json(node.cost)}, '{}'::uuid[], ${textArray(node.topics)}, ${node.solvesRequired}, ${node.posX}, ${node.posY})`,
    `on conflict (slug) do update set name = excluded.name, tier = excluded.tier, branch = excluded.branch,`,
    `  description = excluded.description, cost = excluded.cost, topics = excluded.topics,`,
    `  solves_required = excluded.solves_required, pos_x = excluded.pos_x, pos_y = excluded.pos_y;`,
    "",
  );
}

// `requires` holds uuids, which only exist after the rows above are inserted.
lines.push(
  "-- Resolve tech prerequisites by slug now that every node has an id.",
  "",
);
for (const node of TECH_NODES) {
  if (node.requires.length === 0) continue;
  lines.push(
    `update public.tech_nodes set requires = (`,
    `  select coalesce(array_agg(t.id), '{}'::uuid[]) from public.tech_nodes t where t.slug = any(${textArray(node.requires)})`,
    `) where slug = ${q(node.slug)};`,
    "",
  );
}

// ---------------------------------------------------------------------------
lines.push("-- ---------- blueprints ----------", "");
for (const blueprint of BLUEPRINTS) {
  lines.push(
    `insert into public.blueprints (slug, name, kind, description, base_cost, requires_tech, requires_rep, max_level, default_accent, upkeep_compute, build_minutes)`,
    `values (${q(blueprint.slug)}, ${q(blueprint.name)}, ${q(blueprint.kind)}::public.zoning, ${q(blueprint.description)}, ${json(blueprint.baseCost)},`,
    `  (select coalesce(array_agg(t.id), '{}'::uuid[]) from public.tech_nodes t where t.slug = any(${textArray(blueprint.requiresTech)})),`,
    `  ${blueprint.requiresRep}, ${blueprint.maxLevel}, ${q(blueprint.defaultAccent)}, ${blueprint.upkeepCompute}, ${blueprint.buildMinutes})`,
    `on conflict (slug) do update set name = excluded.name, kind = excluded.kind, description = excluded.description,`,
    `  base_cost = excluded.base_cost, requires_tech = excluded.requires_tech, requires_rep = excluded.requires_rep,`,
    `  max_level = excluded.max_level, default_accent = excluded.default_accent,`,
    `  upkeep_compute = excluded.upkeep_compute, build_minutes = excluded.build_minutes;`,
    "",
  );
}

// ---------------------------------------------------------------------------
lines.push("-- ---------- item definitions ----------", "");
for (const item of ITEM_DEFINITIONS) {
  lines.push(
    `insert into public.item_definitions (slug, name, kind, rarity, description, craftable, cost, requires_rep, requires_tech, base_params)`,
    `values (${q(item.slug)}, ${q(item.name)}, ${q(item.kind)}::public.item_kind, ${q(item.rarity)}::public.rarity, ${q(item.description)}, ${item.craftable}, ${json(item.cost)}, ${item.requiresRep},`,
    `  (select coalesce(array_agg(t.id), '{}'::uuid[]) from public.tech_nodes t where t.slug = any(${textArray(item.requiresTech)})),`,
    `  ${json(item.baseParams)})`,
    `on conflict (slug) do update set name = excluded.name, kind = excluded.kind, rarity = excluded.rarity,`,
    `  description = excluded.description, craftable = excluded.craftable, cost = excluded.cost,`,
    `  requires_rep = excluded.requires_rep, requires_tech = excluded.requires_tech, base_params = excluded.base_params;`,
    "",
  );
}

// ---------------------------------------------------------------------------
lines.push("-- ---------- badges ----------", "");
for (const badge of BADGES) {
  lines.push(
    `insert into public.badges (slug, name, description, rarity, accent, rule)`,
    `values (${q(badge.slug)}, ${q(badge.name)}, ${q(badge.description)}, ${q(badge.rarity)}::public.rarity, ${q(badge.accent)}, ${json(badge.rule)})`,
    `on conflict (slug) do update set name = excluded.name, description = excluded.description,`,
    `  rarity = excluded.rarity, accent = excluded.accent, rule = excluded.rule;`,
    "",
  );
}

// ---------------------------------------------------------------------------
lines.push("-- ---------- problems and test cases ----------", "");
for (const problem of ALL_PROBLEMS) {
  lines.push(
    `insert into public.problems (slug, title, difficulty, topics, statement_md, constraints_md, time_limit_ms, memory_limit_mb, is_public)`,
    `values (${q(problem.slug)}, ${q(problem.title)}, ${q(problem.difficulty)}::public.difficulty, ${textArray(problem.topics)}, ${q(problem.statement)}, ${q(problem.constraints)}, ${problem.timeLimitMs ?? 2000}, ${problem.memoryLimitMb ?? 256}, true)`,
    `on conflict (slug) do update set title = excluded.title, difficulty = excluded.difficulty, topics = excluded.topics,`,
    `  statement_md = excluded.statement_md, constraints_md = excluded.constraints_md,`,
    `  time_limit_ms = excluded.time_limit_ms, memory_limit_mb = excluded.memory_limit_mb;`,
    "",
    `-- Replace this problem's cases wholesale, so an edited expectation cannot linger.`,
    `delete from public.testcases where problem_id = (select id from public.problems where slug = ${q(problem.slug)});`,
    "",
  );

  problem.testcases.forEach((testcase, index) => {
    lines.push(
      `insert into public.testcases (problem_id, input, expected, is_sample, weight, ordinal)`,
      `values ((select id from public.problems where slug = ${q(problem.slug)}), ${q(testcase.input)}, ${q(testcase.expected)}, ${testcase.isSample}, ${testcase.weight ?? 1}, ${index});`,
      "",
    );
  });
}

lines.push("commit;", "");

const target = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(target, lines.join("\n"), "utf8");

console.log(
  `Wrote supabase/seed.sql — ${ALL_PROBLEMS.length} problems, ` +
    `${ALL_PROBLEMS.reduce((n, p) => n + p.testcases.length, 0)} cases, ` +
    `${TECH_NODES.length} tech nodes, ${BLUEPRINTS.length} blueprints, ` +
    `${ITEM_DEFINITIONS.length} items, ${BADGES.length} badges.`,
);
